---

- hosts: chroot
  connection: chroot

  tasks:
  - name: update resolv.conf
    shell: 'echo "nameserver 8.8.8.8" > /etc/resolv.conf'

  - name: install cloud-init
    apt:
      name: cloud-init
      state: present

  - name: cloud-init config
    template:
      src: templates/cloud.cfg
      dest: /etc/cloud/cloud.cfg
      mode: 0644
      owner: root
      group: root

  - name: cloud-init datasource
    template:
      src: templates/90_dpkg.cfg
      dest: /etc/cloud/cloud.cfg.d/90_dpkg.cfg
      mode: 0644
      owner: root
      group: root


  - name: install conda
    include_tasks: conda.yml 

  - name: install software
    include_tasks: software.yml
