---

  - name: update apt cache
    apt: update_cache=yes

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
      - bzip2
      - git
      - bioperl
      - libssl-dev
      - hdf5-tools
      - libdatetime-perl
      - libxml-simple-perl
      - libdigest-md5-perl
      - pkg-config
      - python-setuptools
      - python3-setuptools
      - python3-pip
      - cmake
      - default-jre
      - gnuplot-x11
      - texlive
      - texlive-latex-extra
      - artemis
      - libfreetype6-dev

## Software from ONT

  - name: add nanopore key
    apt_key: url=https://mirror.oxfordnanoportal.com/apt/ont-repo.pub state=present

  - name: add nanopore repo
    apt_repository:
      repo: deb http://mirror.oxfordnanoportal.com/apt xenial-stable non-free
      state: present
      filename: nanoporetech

  - name: install python3-ont-fast5-api
    apt: name=python3-ont-fast5-api state=present allow_unauthenticated=yes

  - name: minknow
    apt: name=minknow-nc state=present allow_unauthenticated=yes

  - name: install ont-albacore wheel
    pip: name=https://mirror.oxfordnanoportal.com/software/analysis/ont_albacore-2.3.3-cp35-cp35m-manylinux1_x86_64.whl executable=pip3
    become: yes
    become_user: "{{ localuser }}"

  - name: install guppy
    apt: name=ont-guppy state=present

  - name: artic primer schemes github
    git: repo=https://github.com/artic-network/primer-schemes.git dest=/artic force=yes

  - name: install cython
    pip: name=cython executable=/home/{{ localuser }}/miniconda3/bin/pip
    become: yes
    become_user: "{{ localuser }}"

  - name: artic pipeline
    pip: name='git+https://github.com/artic-network/fieldbioinformatics.git' executable=/home/{{ localuser }}/miniconda3/bin/pip
    become: yes
    become_user: "{{ localuser }}"
